#!/bin/bash

Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    local command=(
        eos_yad --title="TMUX keybindings" --no-buttons --geometry=400x345-15-400 --list
        --column=key: --column=description: 
        "SESSIONS" ""
        "s" "List sessions" 
        "$" "Name session" 

        ""  "" 
        "WINDOWS"  "" 
        "c"  "create window"
        "w"  "list windows"
        "n"  "next window"
        "p"  "previous window"
        "f"  "find window"
        ","  "name window"
        "ambersand"  "kill window"
        "|"  "vertical split"
        "-"  "horizontal split"

        ""  "" 
        "PANES"  "" 
        "o"  "swap panes"
        "q"  "show pane numbers"
        "x"  "kill pane"
        "+"  "break pane into window (e.g. to select text by mouse to copy)"
        "-"  "restore pane from window"
        "⍽"  "space - toggle between layouts"
        "prefix q" "(Show pane numbers, when the numbers show up type the key to goto that pane)"
        "prefix {" "(Move the current pane left)"
        "prefix }" "(Move the current pane right)"
        "prefix z" "toggle pane zoom"
    )

    "${command[@]}"
}

Main "$@"
